export interface Language {
  HomePageTitle: string;
  SubHomePage: string;
  SelectedProjects: string;
  buttonConversion: string;
  headerPortfolio: string;
  headerAboutUs: string;
  headerContacts: string;
  UA: string;
  EU: string;
  exterior: string;
  interior: string;
  landscape: string;
  all: string;
  mainHomePage: string;
  viewAll: string;
  letsTalk: string;
  joinTeam: string;
  nameLabel: string;
  phoneLabel: string;
  commentLabel: string;
  emailLabel: string;
  linkLabel: string;
  sendRequest: string;
  namePlaceholder: string;
  emailPlaceholder: string;
  phonePlaceholder: string;
  commentPlaceholder: string;
  linkPlaceholder: string;
  address: string;
  whoWeAre: string;
  whatWeDo: string;
  joinOurBuro: string;
  team: string;
  whoWeAreText: string;
  whatWeDo1: string;
  whatWeDo2: string;
  whatWeDo3: string;
  whatWeDo4: string;
  whatWeDo5: string;
  joinOurBuroText: string;
  contacts: string;
  visitUs: string;
  callUs: string;
  writeUs: string;
  nameError: string;
  phoneError: string;
  emailError: string;
  cvlinkError: string;
  commentError: string;
  contactAddress: string;
  contactPhone: string;
  contactEmail: string;
  tour: string;
  tourCategory: string;
  otherProject: string;
  projectName: string,
  projectCategory: string,
  projectLocation: string,
  projectYear: string,
  projectArea: string,
  homaPageProject: string,
  home: string,
}
